### PR TITLE
Change required options to be non-option arguments

### PR DESCRIPTION
**Pull request by luther9**
I've made a few changes that I hope you will like. The biggest change is treating some of the options as subcommands. At least one of 'all', 'upper', 'lower', 'numbers', 'special', and 'own' is required for GoPasswordCreator to do anything useful, so they should be treated as subcommands, not options.

### CODE REVIEW

**Comment by d3xter** [comment]
Thanks for the grammar fixes :D

I'll have a look at it in the evening or tomorrow

**Comment by d3xter** [comment]
I noticed two things:
1. It is not documented, that all/alphanum/... are boolean and can be disabled with "lower=false",
2. Wrong arguments like "lower=Test" create an error in setBoolean and sets the &lower to nil

**Comment by luther9** [comment]
1. I've now added that to README.markdown. (It was already in the Usage message.)
2. The program does catch the error and print it. Is there a problem with that? Please tell me what you believe is wrong, not just what you see.

**Comment by d3xter** [comment]
The parse error of "lower=Blabla" is printed, but "lower" still get disabled

**Comment by luther9** [comment]
After thinking about it, I think that situation should get a better error message and an os.Exit call. Does that answer your concern?

**Comment by d3xter** [comment]
The error message is meaningful, no need to change it.

os.Exit would be one way, the other way would be to display the error and dont disable lower

**Comment by luther9** [comment]
I prefer to use os.Exit. I'd rather not add code that arbitrarily sets the value when it's clear that the user made a mistake.

**Comment by d3xter** [comment]
I'm cool with that

**Pull request merged**
